#
#func_print_head "Install Nginx"
#yum install nginx -y &>>$log_file
#func_stat_check $?
#
#func_print_head "Copy roboshop Config file"
#cp roboshop.conf /etc/nginx/default.d/roboshop.conf &>>$log_file
#func_stat_check $?
#
#func_print_head "Clean Old App content"
#rm -rf /usr/share/nginx/html/* &>>$log_file
#func_stat_check $?
#
#func_print_head "Download App Content"
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>$log_file
#func_stat_check $?
#
#func_print_head "Extracting App Content"
#cd /usr/share/nginx/html &>>$log_file
#unzip /tmp/frontend.zip &>>$log_file
#func_stat_check $?
#
#func_print_head "Start Nginx"
#systemctl enable nginx &>>$log_file
#systemctl restart nginx &>>$log_file
#func_stat_check $?


- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy roboshop config file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Clean Old App content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating a directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download the app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true

