#if [ "$schema_setup" == "mongo" ]; then
#    func_print_head "Copy MongoDB repo"
#    cp ${script_path}/mongo.repo /etc/yum.repos.d/mongo.repo &>>$log_file
#    func_stat_check $?
#
#    func_print_head "Install MongoDB Client"
#    yum install mongodb-org-shell -y &>>$log_file
#    func_stat_check $?
#
#    func_print_head "Load Schema"
#    mongo --host mongodb-dev.rdevopsb72.online </app/schema/${component}.js &>>$log_file
#    func_stat_check $?
#  fi

